// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BoxLoading: typeof import('./src/components/front/BoxLoading.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCasecade: typeof import('element-plus/es')['ElCasecade']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FrontBoxes: typeof import('./src/components/front/FrontBoxes.vue')['default']
    FrontFooter: typeof import('./src/components/front/FrontFooter.vue')['default']
    FrontHeader: typeof import('./src/components/front/FrontHeader.vue')['default']
    FrontLogin: typeof import('./src/components/front/FrontLogin.vue')['default']
    FrontSearchBox: typeof import('./src/components/front/FrontSearchBox.vue')['default']
    FrontTitle: typeof import('./src/components/front/FrontTitle.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Login: typeof import('./src/components/front/Login.vue')['default']
    MenuDropDown: typeof import('./src/components/front/header/MenuDropDown.vue')['default']
    MsgDialog: typeof import('./src/components/front/header/MsgDialog.vue')['default']
    NewsDialog: typeof import('./src/components/front/header/NewsDialog.vue')['default']
  }
}

export { }
